### ISSUE TITLE
Erreur dans le readme.md du PYBStick-ESP32-C3

### ISSUE THREAD

**Issue by dglaude** [mchobby/pyboard-driver#6]
Le readme semble basé sur un copier/coller pour un PYBStick-RP2040, j'ai retiré une référence dans mon fork.
Voir https://github.com/dglaude/pyboard-driver/blob/master/PYBStick-ESP32-C3/readme.md

**Comment by mchobby** [comment]
Tu peux faire un Pull-request comme cela je le réintègre au GitHub d'origine

**Comment by dglaude** [comment]
Je pense que le projet est configuré d'une façon a ne pas accepter de PR...
Il n'y a pas le bouton edit, j'ai du forker à la main pour pouvoir éditer ma copie.
J'ai l'habitude de contribuer à des projets, mais là il y a un truc que je ne comprend pas. :-)

**Comment by mchobby** [comment]
J'ai fais le merge... merci
